### ISSUE TITLE
Polymorphism structure does not make much sense

### ISSUE THREAD

**Issue by rolfvdhulst** [RoboTeamTwente/roboteam_world#20]
The ball should be a seperate Object compared to the robots, which should have their own class. Robots should also have a team boolean to make displays more informative. Currently changing the state index etc. is very frustrating and a lot of work.

**Comment by kJh19** [comment]
one object makes editing the state_index easy since at the moment they all use the same model. when we start using different models, then we should make multiple objects.

**Comment by kJh19** [comment]
boolean could already be added
