### ISSUE TITLE
Adjust KalmanTests to new interface

### ISSUE THREAD

**Issue by HaicoDorenbos** [RoboTeamTwente/roboteam_world#41]
Lukas changed the Kalman interface in Initial cleanup #38 but did not adjust two test cases in /test/KalmanTest.cpp to the new interface. Therefore we have to decide to either change these test cases to the new interface or remove these two test cases.

The two test cases (not adjusted to the new interface) are included in the fix/KalmanTests branch.

**Comment by rolfvdhulst** [comment]
Note I am removing the relevant classes that are being tested also in #40 so merging that closes this as well.

**Comment by rolfvdhulst** [comment]
This was fixed in a previous pr.
